In [1]:
#question 1.1
import numpy as np
array_1d = np.arange(5, 26)
print("1D array from 5 to 25:", array_1d)

1D array from 5 to 25: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [2]:
#question 1.2
import numpy as np
array_2d = np.random.randint(10, 51, size=(3, 4))
print("2D array with random integers between 10 and 50:\n", array_2d)

2D array with random integers between 10 and 50:
 [[23 43 42 30]
 [14 20 48 28]
 [26 44 50 47]]


In [5]:
#question 2.1
import numpy as np
array_1d = np.arange(5, 26)
print("1D array shape:", array_1d.shape)
print("1D array size:", array_1d.size)
print("1D array data type:", array_1d.dtype)

1D array shape: (21,)
1D array size: 21
1D array data type: int64


In [6]:
#question 2.2
import numpy as np
array_2d = np.random.randint(10, 51, size=(3, 4))
print("2D array shape:", array_2d.shape)
print("2D array size:", array_2d.size)
print("2D array data type:", array_2d.dtype)

2D array shape: (3, 4)
2D array size: 12
2D array data type: int32


In [9]:
#question 3.1
import numpy as np
array1 = np.array([2, 4, 6, 8, 10])
array2 = np.array([1, 3, 5, 7, 9])
print("Array1:", array1)
print("Array2:", array2)

#question 3.2
addition = array1 + array2
print("Addition:", addition)

subtraction = array1 - array2
print("Subtraction:", subtraction)

multiplication = array1 * array2
print("Element-wise multiplication:", multiplication)

division = array1 / array2
print("Element-wise division:", division)


Array1: [ 2  4  6  8 10]
Array2: [1 3 5 7 9]
Addition: [ 3  7 11 15 19]
Subtraction: [1 1 1 1 1]
Element-wise multiplication: [ 2 12 30 56 90]
Element-wise division: [2.         1.33333333 1.2        1.14285714 1.11111111]


In [11]:
#question 4.1
import numpy as np
array_2d = np.arange(1, 10).reshape(3, 3)
print("2D array:\n", array_2d)

#question 4.2
result_array = array_2d * 5
print("Result of multiplying the 2D array by 5:\n", result_array)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Result of multiplying the 2D array by 5:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [14]:
# question 5.1
import numpy as np
array_2d = np.arange(10, 26).reshape(4, 4)
print("2D array:\n", array_2d)
#question 5.2
second_row = array_2d[1, :]
print("Second row:", second_row)
last_column = array_2d[:, -1]
print("Last column:", last_column)
#question 5.3
array_2d[0, :] = 0
print("2D array after replacing the first row with zeros:\n", array_2d)


2D array:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
Second row: [14 15 16 17]
Last column: [13 17 21 25]
2D array after replacing the first row with zeros:
 [[ 0  0  0  0]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [15]:
#question 6.1
import numpy as np
array_1d = np.random.randint(20, 41, size=10)
print("1D array with random integers between 20 and 40:", array_1d)

#question 6.2
greater_than_30 = array_1d[array_1d > 30]
print("Elements greater than 30:", greater_than_30)


1D array with random integers between 20 and 40: [26 33 34 33 29 28 23 29 23 40]
Elements greater than 30: [33 34 33 40]


In [16]:
#question 7.1
import numpy as np
array_1d = np.arange(11, 23)
print("1D array:", array_1d)

#question 7.2
array_2d = array_1d.reshape(3, 4)
print("Reshaped 2D array:\n", array_2d)


1D array: [11 12 13 14 15 16 17 18 19 20 21 22]
Reshaped 2D array:
 [[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [17]:
#question 8.1
matrix_A = np.array([2, 4, 6, 8, 10])
matrix_B = np.array([1, 3, 5, 7, 9])
matrix_multiplication = np.dot(matrix_A, matrix_B)
print("Matrix Multiplication (A * B):\n", matrix_multiplication)

#question 8.2
transpose_A = np.transpose(matrix_A)
print("Transpose of Matrix A:\n", transpose_A)


Matrix Multiplication (A * B):
 190
Transpose of Matrix A:
 [ 2  4  6  8 10]


In [18]:
#question 9.1
import numpy as np
array_1d = np.random.randint(10, 61, size=15)
print("1D array with random integers between 10 and 60:", array_1d)
#question 9.2
mean_value = np.mean(array_1d)
print("Mean:", mean_value)

median_value = np.median(array_1d)
print("Median:", median_value)

std_deviation = np.std(array_1d)
print("Standard Deviation:", std_deviation)


1D array with random integers between 10 and 60: [45 56 27 42 47 56 23 49 15 51 60 33 21 57 19]
Mean: 40.06666666666667
Median: 45.0
Standard Deviation: 15.088479784995645
